use crate::cli::InitArgs;
use crate::config::Config;
use std::process::Command;
use tracing::info;

/// Labels to create with their colors and descriptions
const LABELS: &[(&str, &str, &str)] = &[
    (
        "p0",
        "B60205",
        "Critical priority - security vulnerability or data loss",
    ),
    ("p1", "D93F0B", "High priority - significant bug or risk"),
    ("p2", "FBCA04", "Medium priority - should be addressed"),
    ("polyrev", "1D76DB", "Generated by polyrev automated review"),
    (
        "automated-review",
        "5319E7",
        "Created by automated code review",
    ),
];

pub fn execute(args: InitArgs) -> anyhow::Result<()> {
    // Determine repo from args or config
    let repo = if let Some(r) = args.repo {
        r
    } else if args.config.exists() {
        let config = Config::load(&args.config)?;
        config.github.repo.ok_or_else(|| {
            anyhow::anyhow!(
                "No repository specified. Use --repo owner/repo or set github.repo in config"
            )
        })?
    } else {
        anyhow::bail!("No repository specified. Use --repo owner/repo");
    };

    info!("Initializing labels for {}", repo);

    if args.dry_run {
        println!("\nDRY RUN - would create the following labels:\n");
        for (name, color, description) in LABELS {
            println!("  {} (#{}) - {}", name, color, description);
        }
        return Ok(());
    }

    let mut created = 0;
    let mut existed = 0;
    let mut errors = 0;

    for (name, color, description) in LABELS {
        match create_label(&repo, name, color, description) {
            Ok(LabelResult::Created) => {
                info!("Created label: {}", name);
                created += 1;
            }
            Ok(LabelResult::Exists) => {
                info!("Label already exists: {}", name);
                existed += 1;
            }
            Err(e) => {
                info!("Failed to create label {}: {}", name, e);
                errors += 1;
            }
        }
    }

    println!(
        "\nDone: {} created, {} already existed, {} errors",
        created, existed, errors
    );

    if errors > 0 {
        anyhow::bail!("Some labels failed to create");
    }

    Ok(())
}

enum LabelResult {
    Created,
    Exists,
}

fn create_label(
    repo: &str,
    name: &str,
    color: &str,
    description: &str,
) -> anyhow::Result<LabelResult> {
    let output = Command::new("gh")
        .args([
            "label",
            "create",
            name,
            "--repo",
            repo,
            "--color",
            color,
            "--description",
            description,
        ])
        .output()?;

    if output.status.success() {
        return Ok(LabelResult::Created);
    }

    let stderr = String::from_utf8_lossy(&output.stderr);

    // Check if label already exists
    if stderr.contains("already exists") {
        return Ok(LabelResult::Exists);
    }

    Err(anyhow::anyhow!("{}", stderr.trim()))
}
